### ISSUE TITLE
dLAN500-ROOT works on Devolo dlan 200 AV Wireless N with v.5 firmware (should work on v.6 too)

### ISSUE THREAD

**Issue by KrzysztofKaspruk** [lawl/devolotools#2]
Just wanted to let you know that dLAN500-ROOT works on Devolo dlan 200 AV Wireless N with v.5 firmware as well.

It should also work on v.6 firmware, since timestamps of squashfs filesystem are older than those of dlan 500 AV Wireless+ v2.0.2 that you've provided.

~~Note that the latter device (dlan 500 AV Wireless+) has got an OpenWRT port.~~
dlan **Pro** 500 Wireless+ is the one with OpenWRT port.

Wish that there was one for my device as well (I'd like to unbridge ethernet and wifi and put wifi on separate subnet with local udhcpd on the PLC adapter, busybox seems to have that compiled in. Persistence would be a major pain in the neck, I wish I could do without reflashing the device).

Anyway, thank you for your work. It saved me probably a great deal of reversing.

(Script for decoding configuration file works as well, though there's hardly anything useful in it)

**Comment by lawl** [comment]
Cool! Thanks for letting me know, I've updated the readme to include this.

**Comment by KrzysztofKaspruk** [comment]
Just wanted to report dLAN500-ROOT works as well on dlan 500 AV Wireless+ firmware version: 3.1.0 (2014-09-12).

btw. on OpenWRT forums somebody sucesfully uses configuration for Devolo dLAN Pro 1200+ with altered MTD partitions [to flash Devolo dLAN 1200+ WiFi ac (non-Pro)](https://forum.openwrt.org/t/support-for-devolo-dlan-1200-wifi-ac-non-pro-version/11007). I hope the relation between Devolo dLAN 500 AV Wireless+ and Pro version is the same as between Devolo dLAN 1200+ WiFi ac and Devolo dLAN Pro 1200+ and by altering flash layout I could run OpenWRT on mine as well. Will be trying that.
